export const FOOD_FIND_ALL = 'FOOD_FIND_ALL';
export const FOOD_FIND_SIMPLE_ALL = 'FOOD_FIND_SIMPLE_ALL';
export const FOOD_FIND_BY_ID = 'FOOD_FIND_BY_ID';
export const FOOD_PAGINATED_SEARCH = 'FOOD_PAGINATED_SEARCH';
