export const CLIENTE_FIND_ALL = 'CLIENTE_FIND_ALL';
export const CLIENTE_FIND_SIMPLE_ALL = 'CLIENTE_FIND_SIMPLE_ALL';
export const CLIENTE_FIND_BY_ID = 'CLIENTE_FIND_BY_ID';
export const CLIENTE_PAGINATED_SEARCH = 'CLIENTE_PAGINATED_SEARCH';
