export const CATEGORIA_FIND_ALL = "CATEGORIA_FIND_ALL";
export const CATEGORIA_FIND_SIMPLE_ALL = "CATEGORIA_FIND_SIMPLE_ALL";
export const CATEGORIA_FIND_BY_ID = "CATEGORIA_FIND_BY_ID";
export const CATEGORIA_PAGINATED_SEARCH = "CATEGORIA_PAGINATED_SEARCH";
